apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-team-overlay
  namespace: flux-system
spec:
  interval: 60s
  path: ./apps/team-overlay
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system