apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo-deployment
spec:
  template:
    spec:
      containers:
      - name: podinfo
        env:
        - name: PODINFO_UI_COLOR
          value: "#007300"